#spring.application.name=pay
spring:
  application:
    name: payment
  datasource:
    url: jdbc:mysql://${host}/${database}?&serverTimezone=Asia/Seoul
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  secret: ${secret}
  expiration: ${expiration}